### ISSUE TITLE
replace loaded segmentation mask

### ISSUE THREAD

**Issue by ngreenwald** [ParkerICI/mantis-viewer#17]
It's totally possible that I'm missing something, but it appears that reloading a new segmentation mask when a previous one has already been loaded currently doesn't do anything. It gives a warning about losing previously gated populations, but I don't believe the new one gets loaded.

Is there a way to first remove an existing segmentation mask prior to reloading a different one? This is for comparing multiple different segmentations on the same image set.

**Comment by rj3d** [comment]
Thanks for the report!

If you try to load a new segmentation file while one is already loaded it should replace the old one. If it doesn't then this is a bug. I'll look into this and see if I can reproduce and, if so, what's going on.

In the interim, you should be able to use the clear segmentation button in the image controls pane to clear the segmentation. Once the segmentation has been cleared you should be able to load a new segmentation file.

**Comment by ngreenwald** [comment]
Yes, using the clear segmentation button does in fact clear the segmentation and allow a different mask to be reloaded. Going to matnis->import-> segmentation gives the same warning message as attempting to clear, but doesn't actually replace the existing segmentation

**Comment by rj3d** [comment]
Awesome! Glad that the clear segmentation button works as a workaround. The replacing not working sounds like a bug though, I'll look into fixing it!
