### ISSUE TITLE
add inset for zoom location

### ISSUE THREAD

**Issue by ngreenwald** [ParkerICI/mantis-viewer#18]
It would be great if there was a little window at the top, similar to FIJI, to show where in an image the current view is when zoomed larger than 100%. 

See attached for an example in upper left-hand corner of FIJI

![image](https://user-images.githubusercontent.com/13770365/73780334-248fb480-4743-11ea-9f44-4baa7052246a.png)

**Comment by rj3d** [comment]
Good idea! We can definitely add something like that. Thanks for the suggestion!
