### ISSUE TITLE
add option to hide non-highlighted segmentation boundaries

### ISSUE THREAD

**Issue by ngreenwald** [ParkerICI/mantis-viewer#20]
Currently there is the option to give specific cell populations a color, and overlay that color over the segmentation. However, there doesn't appear to be a way to turn off the display for non-selected cells. 

It would be great to add a toggle that removes the default rendering of segmentations, and only keeps those that have been given a specific color 
![image](https://user-images.githubusercontent.com/13770365/75618870-e65e9880-5b28-11ea-88fd-00b1e40da86c.png)

**Comment by rj3d** [comment]
If I'm understanding this correctly, you want to turn off the segmentation outlines for all cells, and leave only the segmentation outlines for selected populations or regions? Mantis does currently support this. You can turn off the default segmentation outlines by turning 'Segmentation Outline Alpha' down to 0 in the 'Image Controls' panel on the left of the image display.

Hope this helps! Let me know if I'm not understanding the request though.

**Comment by ngreenwald** [comment]
That's perfect!
