### ISSUE TITLE
Resize display when zoomed

### ISSUE THREAD

**Issue by ngreenwald** [ParkerICI/mantis-viewer#23]
It would be nice if Mantis would resize the display to better fit the available screen space once zoom has been activated. If non-square images are loaded, only a small amount of the available screen space is used to display the image, as see in the screenshot below

![image](https://user-images.githubusercontent.com/13770365/78691629-afa93a00-78ad-11ea-882f-b289212bf6fd.png)

**Comment by rj3d** [comment]
I like this idea! I'll be sending you all an email shortly about the next release, but I'll add this to the list of improvements for the next release.

**Comment by ngreenwald** [comment]
Great, thanks!

**Comment by rj3d** [comment]
@ngreenwald I just uploaded a new build for you to play with that adds this feature. Let me know if you find any bugs!

https://github.com/ParkerICI/mantis-viewer/releases/tag/v1.1.0-alpha.3

**Comment by rj3d** [comment]
@ngreenwald just pushed another new build that resizes the display to take up all available space when zoomed.

https://github.com/ParkerICI/mantis-viewer/releases/tag/v1.1.0-alpha.4

**Comment by ngreenwald** [comment]
Okay awesome! I'll take a look tonight

**Comment by ngreenwald** [comment]
This is awesome!

**Comment by rj3d** [comment]
Glad you like it!
