### ISSUE TITLE
Add option to control image blurring

### ISSUE THREAD

**Issue by ngreenwald** [ParkerICI/mantis-viewer#27]
It looks like the image data is being blurred somehow when it's displayed in Mantis. Is there a way to control this behavior, or if not, how much work would it be to add a tunable parameter?

**Comment by rj3d** [comment]
Could you show me some examples with screenshots? The only time that any blurring should be happening is when we're downsampling.

**Comment by ngreenwald** [comment]
Sure thing, here's a side-by-side of Mantis and FIJI: 
![image](https://user-images.githubusercontent.com/13770365/81759894-d04f4b80-947a-11ea-9bc6-586dacd0d4e1.png)

I attached the FOV, the screen shot is from the very very bottom left hand corner of the image. 
[NAKATPASE.tif.zip](https://github.com/ParkerICI/mantis-viewer/files/4619216/NAKATPASE.tif.zip)

**Comment by rj3d** [comment]
Thanks Noah! I'll put this on the list of things to look into for this release.

**Comment by ngreenwald** [comment]
Awesome thanks

**Comment by rj3d** [comment]
This is fixed and will be released in v1.1.0-alpha.9. Thanks for finding this Noah!

**Comment by rj3d** [comment]
Reopening because I'm not sure I actually fixed it. It seems like this might not be possible to do with v4 of PixiJS. We're planning to upgrade to v5, which seems like it might have better support for this, but there are some breaking changes which will take time to figure out how to integrate.

**Comment by rj3d** [comment]
I upgraded PixiJS to v5 and was able to fix this. In the next alpha users will have the option to enable or disable image blurring from the preferences window.
