### ISSUE TITLE
Only display error message if populations not successfully imported

### ISSUE THREAD

**Issue by ngreenwald** [ParkerICI/mantis-viewer#29]
I got the following message about not all features being imported. It looks like it's displayed even if all of the cells were successfully imported

![image](https://user-images.githubusercontent.com/13770365/84718512-98ca3800-af2d-11ea-8e4d-da6e6c303493.png)

**Comment by rj3d** [comment]
Thanks for posting this! This should be fixed in the v1.1.0-alpha.10 release I just uploaded.
