### ISSUE TITLE
Issue with selecting region of interest on image using mouse

### ISSUE THREAD

**Issue by jkgopa** [ParkerICI/mantis-viewer#31]
When I try to highlight a region of interest using my mouse as described ( https://mantis.parkerici.org/populations/ ), the lasso tool never lets go, even after I release the mouse button, and the region is never selected. I did not have this issue earlier today, but now I have this issue recurrently even after re-downloading mantis-viewer. Do you have any tips on how to resolve this issue?

**Comment by jkgopa** [comment]
I forgot to open the segmentation labels file before selecting the region. That corrects my issue

**Comment by rj3d** [comment]
Glad you figured it out!
