### ISSUE TITLE
Can't import regions from tiffs without segmentation masks

### ISSUE THREAD

**Issue by ngreenwald** [ParkerICI/mantis-viewer#55]
I ran into an issue today where I was trying to load a new project that had spatial data encoded as a regions file. When going to the load new project interface, if I specified a regions tiff for the project without a segmentation mask, the image data loaded but not the regions. Same thing for loading a regions file in an individual image without a segmentation mask: it would accept the file, but then nothing happened. It was only if there were already segmentations loaded that the regions could get loaded in. 

Not sure if this is intentional, and if the thought is that regions should define regions of segmented cells, or accidental based on the hierarchy of the data structure. Either way, having an error message pop up to explain would be helpful, or updating the documentation.

**Comment by rj3d** [comment]
This is accidental, I will get this fixed! Thanks for the report.

**Comment by rj3d** [comment]
Fixed in the release [https://github.com/ParkerICI/mantis-viewer/releases/tag/v1.2.2-rc.1](https://github.com/ParkerICI/mantis-viewer/issues/v1.2.2-rc.1).
