### ISSUE TITLE
Provide names for regions

### ISSUE THREAD

**Issue by ngreenwald** [ParkerICI/mantis-viewer#56]
Currently there is no way to provide metadata for the regions supplied in a file. It would be great if there was a way to provide a csv linking each integer in the regions tiff to a descriptive name, so that they don't need to be manually edited in each image in the project.

**Comment by rj3d** [comment]
Good idea, and should be easy to do. I'll add this to the short list of planned new features.

**Comment by rj3d** [comment]
This is added on v1.2.2-rc.2.

https://github.com/ParkerICI/mantis-viewer/releases/tag/v1.2.2-rc.2
