### ISSUE TITLE
Image moves when turning off all channels

### ISSUE THREAD

**Issue by ngreenwald** [ParkerICI/mantis-viewer#59]
When all of the channels are turned off, the entire image shifts slightly down. This is due to the `No markers visible` text that gets placed on the top of the display. However, when trying to toggle image channels on and off, this results in the populations shifting slightly, which makes it harder to map up marker expression with a specific population. 

If the text was placed elsewhere, or if the whitespace for the text was always there, independent of the text being displayed, it wouldn't affect the layout of the canvas. 

https://user-images.githubusercontent.com/13770365/166335587-4ffe7908-fdb1-4f2f-b5ac-6db5e0d23b4b.mov

**Comment by rj3d** [comment]
The original point of this message was so that users wouldn't get confused if the image was blank. I think I'll remove the message unless there are no markers and no populations. Would it be more helpful for this use case if the background was black instead of white?

**Comment by rj3d** [comment]
This is fixed on v1.2.2-rc.2.

https://github.com/ParkerICI/mantis-viewer/releases/tag/v1.2.2-rc.2
