### ISSUE TITLE
Add option for pixel populations tooltip

### ISSUE THREAD

**Issue by ngreenwald** [ParkerICI/mantis-viewer#60]
One really nice option when looking at segmented data is the tooltip that pops up at the top showing what population the moused-over cell belongs to:

![image](https://user-images.githubusercontent.com/13770365/167199724-0a92488f-e852-4c98-9162-c238c5e86bf2.png)
This is helpful when there are tons of different colors, because it makes it easy to identify the cell phenotype, rather than needing to mouse over each individual population until the right one lights up. 

It would be nice to have this same option when mousing over individual pixel-level populations:
![image](https://user-images.githubusercontent.com/13770365/167200885-9d7727b6-ddee-45e1-9385-300c9eb8ee21.png)
This would allow the user to quickly figure out the label of a pixel population of interest. 

Some potential problems: 
- There might be performance issues due to the large number of pixels
- It might be challenging to have an attractive UI due to the tooltip constantly changing as the mouse is moved even slightly, due to the small size of individual pixels. For our use case, we tend to have pixels in the same neighborhood that have the same population label, but I imagine this might not be true for everyone. 

Definitely not a necessity, more of the nice-to-have category

**Comment by rj3d** [comment]
I think I understand. By individual pixel level populations do you mean populations that have been imported with a labeled tiff as a region or set of regions? If so I think this should be doable.

I'm thinking we could display the data in the legend, but possibly as a separate list for moused over regions in addition to the list for moused over segments. That way there would be a distinction between regions and segment population membership for users who use regions to find populations of segments.

Also, it feels like the legend might be getting a little busy at this point. It might be good to break out most of the information into a little pane outside of the image.

**Comment by ngreenwald** [comment]
Yes exactly. We generate a tiff where each pixel has been assigned to a region, prior to segmentation.
Then we look at those regions to see what the co-expression is with the markers in our panel to make sure everything lines up. 

We have a second step where we load in a segmentation mask, along with a tiff containing regions. However, in this case we have defined the regions such that all of the pixels within each segmentation mask belong to the same region. This is the one that currently works great out of the box to allow us to identify cell populations.

**Comment by rj3d** [comment]
Makes sense, shouldn't be too hard to add! I'll throw it on the short list of features to add.

**Comment by rj3d** [comment]
Feature added in 1.2.2-rc.4.
