### ISSUE TITLE
Tooltip doesn't display segmentation region for multiple images in project

### ISSUE THREAD

**Issue by ngreenwald** [ParkerICI/mantis-viewer#61]
When multiple images are loaded as part of a project, only the first image will display the tooltip showing which region the segmentation has been assigned to. After switching to a new image, the regions no longer show up in the tooltip, only the segmentation id

https://user-images.githubusercontent.com/13770365/167315592-8731e7a2-7d0e-45ae-948d-ddef5a70b751.mov

**Comment by rj3d** [comment]
That's a weird one! Thanks for reporting, I'll get this fixed.

**Comment by rj3d** [comment]
Fixed in 1.2.2-rc.3!
