### ISSUE TITLE
Scroll drag resets when mouse leaves canvas

### ISSUE THREAD

**Issue by ngreenwald** [ParkerICI/mantis-viewer#63]
When using the mouse to drag the viewing pane around, if the mouse leaves the pane, the scroll resets back to the original location before scrolling started, rather than just stopping the scroll at the current location

https://user-images.githubusercontent.com/13770365/169143348-87b75b21-8155-4e5b-b4dc-3148c3acdcc6.mov

**Comment by rj3d** [comment]
Good find! Bug filed.

**Comment by rj3d** [comment]
Fixed in 1.2.2-rc.4.
