### ISSUE TITLE
Fix seed for population color mapping

### ISSUE THREAD

**Issue by ngreenwald** [ParkerICI/mantis-viewer#64]
Currently, each image in a dataset will have a different mapping between populations and colors. It would be nice if this was set once, project-wide, to enable consistent colors across images.

**Comment by rj3d** [comment]
This has been requested by a few users. It's on my short list and I should get to it in the next couple of weeks.

**Comment by rj3d** [comment]
Fixed in [v1.2.2-rc.5](https://github.com/ParkerICI/mantis-viewer/releases/tag/v1.2.2-rc.5).
