### ISSUE TITLE
Zoom scroll is too slow

### ISSUE THREAD

**Issue by ngreenwald** [ParkerICI/mantis-viewer#65]
The default setting for the scroll wheel to zoom in and out is a bit too slow, as it takes a long time to zoom in on a large image. It would be nice if this was made a bit more sensitive, or if the user could modify this parameter

**Comment by rj3d** [comment]
Good to know! Created a ticket to allow users to configure the zoom speed.

**Comment by rj3d** [comment]
Feature added in 1.2.2-rc.4.
