### ISSUE TITLE
Importing segmentation features stalls for multiple features in large projects

### ISSUE THREAD

**Issue by ngreenwald** [ParkerICI/mantis-viewer#71]
Just started playing around with importing pre-computed segmentation statistics, the feature is awesome! Being able to mouse over a cell and see the computed features is super useful for downstream analysis. 

Importing a CSV with FOV, label, and 1 feature is basically instant. However, importing a CSV with 4 features stalls, and I have to restart mantis. It seems to be related to larger projects: using a project with only 2 images, it works fine, but the one I currently have contains 18 images. Maybe there's some sort of nested for loop that's causing poor scaling?

**Comment by rj3d** [comment]
Glad the feature is useful, and thanks for reporting!

Could you send me the CSV file you're using so I can get an idea for the number of segments?
