### ISSUE TITLE
Export images without labels

### ISSUE THREAD

**Issue by akedarg** [ParkerICI/mantis-viewer#98]
Dear Mantis team,
I have found your software useful. But when i export the png image, the labels are always present at the left top (see image attached). Is there a way to export the images without these labels? because it's taking considerable amount of area in the image and it's unnecessary

thanks,
Kedar
![3_concentration_post_Single](https://github.com/CANDELbio/mantis-viewer/assets/135859852/ce99b3c3-cd20-44fd-88b3-3e2d4461e0d9)

**Comment by yuv345** [comment]
Hi Kedar,
Under _Image Controls_ you can deselect the checkboxes for _Show Channels in Legend_ and _Show Populations in Legend_ to remove the legend before exporting
